FROM collabora/code:latest

ENV domain futurenhs\\.cds\\.co\\.uk

COPY ./coolwsd.xml /etc/coolwsd/coolwsd.xml
COPY ./proof_key /etc/coolwsd/proof_key
COPY ./proof_key.pub /etc/coolwsd/proof_key.pub
COPY ./start-collabora-online.sh /
