FROM collabora/code:latest

ENV domain futurenhs\\.cds\\.co\\.uk

COPY ./loolwsd.xml /etc/loolwsd/loolwsd.xml
COPY ./proof_key /etc/loolwsd/proof_key
COPY ./proof_key.pub /etc/loolwsd/proof_key.pub
COPY ./start-collabora-online.sh /
